#
FROM davegill/wrf-coop:fifthtry
MAINTAINER Dave Gill <gill@ucar.edu>

#	DO NOT CHANGE UNDERSCORE GIT STRINGS
#	THESE ARE USED FOR JENKINS TESTING

RUN git clone _GIT_URL_ WRF \
  && cd WRF \
  && git checkout _GIT_BRANCH_ \
  && cd ..

RUN curl -SL https://www2.mmm.ucar.edu/wrf/dave/script.tar | tar -xC /wrf

VOLUME /wrf
CMD ["/bin/tcsh"]
